Add desktop version, fix contact background, add animations on language
smunoz1988/Portfolio-mobile-first pull request #5
Opened 2023-02-23 17:48 UTC by smunoz1988

Changes:

- add desktop version.
- fix main and about sections backgrounds.
- add animations on languages.
- fix media queries for desktop version.

2023-02-23 19:06 UTC, shella12 requested changes
Hi @smunoz1988 , 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/QW9DYS2fsdORhO9Phu/giphy.gif"/>

## Highlights
- All linters passed ✅ 
- Professional README.md ✅   
- Correct use of git flow ✅ 
- Nice animation effects ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 19:06 UTC, shella12 commented on index.html
> +            <img class="cardsection" src="images/work1.png" alt="SnapshootPortfolio">
- [ ] Please align the grey circles of the work info section, of the project cards to make them look like [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=Z0umLtHjW2jvzRBK-0) as it is the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#project-requirements) of the project to make your portfolio look like figma design

> You need to make sure that your dekstop version looks like the one in the Figma design template that you chose.

**_Figma Design_**

<img width="209" alt="Screenshot 2023-02-23 at 11 25 58 PM" src="https://user-images.githubusercontent.com/44798044/220997323-b6c595df-2f24-4110-88b4-4a10e7882914.png">

**_Your Design_**

<img width="328" alt="Screenshot 2023-02-23 at 11 07 01 PM" src="https://user-images.githubusercontent.com/44798044/220997393-99c99a87-698c-4e12-8e85-602857f716c9.png">

2023-02-23 19:06 UTC, shella12 commented on index.html
> +            <img class="cardsection" src="images/work2.png" alt="SnapshootPortfolio">
- [ ] Please make sure the tech stack list of the project cards in the work info section, is aligned in a straight line with the rest of the content, to make them look like [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=Z0umLtHjW2jvzRBK-0) as it is the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#project-requirements) of the project to make your portfolio look like figma design

> You need to make sure that your dekstop version looks like the one in the Figma design template that you chose.

**_Figma Design_**

<img width="174" alt="Screenshot 2023-02-23 at 11 37 55 PM" src="https://user-images.githubusercontent.com/44798044/221000287-aac4a823-a98e-474e-8a39-cd9666a535d8.png">

<img width="285" alt="Screenshot 2023-02-23 at 11 37 47 PM" src="https://user-images.githubusercontent.com/44798044/221000263-5909edd3-844b-4ea6-b5f2-e8dd6714dae3.png">


**_Your Design_**

<img width="288" alt="Screenshot 2023-02-23 at 11 04 49 PM" src="https://user-images.githubusercontent.com/44798044/221000885-5755888f-2f57-4057-b3d6-a5491522dd2d.png">

<img width="382" alt="Screenshot 2023-02-23 at 11 07 11 PM" src="https://user-images.githubusercontent.com/44798044/221000337-22f9317f-8653-4b6e-9a65-969b335f3b0d.png">

2023-02-23 19:06 UTC, shella12 commented on styles/style.css
> +
- [ ] Please make sure to align the header navigation and main content in such a way that the main content comes in the center of the nav links and logo in the desktop version and they are on top of the content in the mobile version, just like [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=Z0umLtHjW2jvzRBK-0)

**_Figma Design_**

<img width="551" alt="Screenshot 2023-02-23 at 11 47 09 PM" src="https://user-images.githubusercontent.com/44798044/221002457-869afd88-d28a-4af1-bcb6-7e2e30ba1f97.png">


<img width="145" alt="Screenshot 2023-02-23 at 11 59 07 PM" src="https://user-images.githubusercontent.com/44798044/221004705-1208e92d-7e7a-45bc-95ed-5c9ab8a33d04.png">

**_Your design_**

<img width="1175" alt="Screenshot 2023-02-23 at 11 06 32 PM" src="https://user-images.githubusercontent.com/44798044/221002624-365df47e-d324-49fa-b2a9-a666f651d027.png">


<img width="364" alt="Screenshot 2023-02-23 at 11 05 48 PM" src="https://user-images.githubusercontent.com/44798044/221004749-776a654c-9611-4be3-9da3-2f0b78944127.png">


- [ ] Please make sure the color of the nav links is `#172b4d` instead of `#7f8cff` just like in the [figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=xA4BcGNoZrgADDYk-0) as it is the[ requirement](#7f8cff) of the project to stick to the figma design: 

> You must replicate the design as much as possible (e.g., font, colors, images, text, margins) using [the info from the Figma templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

**_Figma Design_**

<img width="150" alt="Screenshot 2023-02-23 at 11 55 36 PM" src="https://user-images.githubusercontent.com/44798044/221003584-1f6dafa6-ea2b-4cbb-bf5a-e9cdf73f8c2c.png">

**_Your design_**

<img width="384" alt="Screenshot 2023-02-23 at 11 56 09 PM" src="https://user-images.githubusercontent.com/44798044/221003710-c6bbfb0b-1dfd-452e-a6b8-2e50a280d61c.png">

2023-02-23 19:06 UTC, shella12 commented on styles/style.css
> +  }
- [ ] Please adjust the font-weight of your main title and description paragraph in both desktop and mobile version to make it look like figma

**_Figma Design_**

<img width="361" alt="Screenshot 2023-02-24 at 12 03 34 AM" src="https://user-images.githubusercontent.com/44798044/221005352-40446f9a-8797-420a-8a7d-53d9a07f72d2.png">

<img width="133" alt="Screenshot 2023-02-24 at 12 03 44 AM" src="https://user-images.githubusercontent.com/44798044/221005380-ea50bd7f-ac2f-473c-bc52-42e2ec98a8cf.png">

Your design

<img width="605" alt="Screenshot 2023-02-24 at 12 04 44 AM" src="https://user-images.githubusercontent.com/44798044/221005637-32312e0d-4104-45a9-a8c9-85ee2fbd17c6.png">

<img width="441" alt="Screenshot 2023-02-24 at 12 04 54 AM" src="https://user-images.githubusercontent.com/44798044/221005566-810d1b36-c3f7-497d-9832-339dae70d804.png">

2023-02-24 00:40 UTC, Kossi-stack approved these changes
## Status: Approved ✔️

**Hi @smunoz1988,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-02-24 15:19 UTC, merged